---
apiVersion: v1
kind: Namespace
metadata:
  name: employee-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: employee-api
  name: deployment-employee-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-employee-api
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-employee-api
    spec:
      containers:
      - image: 163487917873.dkr.ecr.us-east-1.amazonaws.com/peoplesuite:employee
        imagePullPolicy: Always
        name: app-employee-api
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: employee-api
  name: service-employee-api
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-employee-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: employee-api
  name: ingress-employee-api
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /peoplesuite/apis/employees
          pathType: Prefix
          backend:
            service:
              name: service-employee-api
              port:
                number: 80
